export const adCategoryOptions = [
  // Technology & Digital  
  { value: "Smartphones", label: "Smartphones" },
  { value: "Laptops", label: "Laptops" },
  { value: "Smartwatches", label: "Smartwatches" },
  { value: "Headphones", label: "Headphones" },
  { value: "Drones", label: "Drones" },
  { value: "VR Headsets", label: "VR Headsets" },
  { value: "Gaming Consoles", label: "Gaming Consoles" },
  { value: "Cameras", label: "Cameras" },
  { value: "Printers", label: "Printers" },
  { value: "Software Tools", label: "Software Tools" },

  // Fashion & Apparel  
  { value: "Men's Shoes", label: "Men's Shoes" },
  { value: "Women's Shoes", label: "Women's Shoes" },
  { value: "Sneakers", label: "Sneakers" },
  { value: "High Heels", label: "High Heels" },
  { value: "Sandals", label: "Sandals" },
  { value: "Handbags", label: "Handbags" },
  { value: "Watches", label: "Watches" },
  { value: "Sunglasses", label: "Sunglasses" },
  { value: "Jewelry", label: "Jewelry" },
  { value: "Men's Clothing", label: "Men's Clothing" },
  { value: "Women's Clothing", label: "Women's Clothing" },
  { value: "Kids' Fashion", label: "Kids' Fashion" },
  { value: "Winter Wear", label: "Winter Wear" },
  { value: "Sportswear", label: "Sportswear" },
  { value: "Luxury Fashion", label: "Luxury Fashion" },

  // Beauty & Cosmetics  
  { value: "Skincare", label: "Skincare" },
  { value: "Makeup", label: "Makeup" },
  { value: "Haircare", label: "Haircare" },
  { value: "Perfumes", label: "Perfumes" },
  { value: "Nail Products", label: "Nail Products" },
  { value: "Beauty Tools", label: "Beauty Tools" },
  { value: "Men's Grooming", label: "Men's Grooming" },
  { value: "Organic Beauty", label: "Organic Beauty" },
  { value: "Tattoo Supplies", label: "Tattoo Supplies" },
  { value: "Cosmetic Surgery", label: "Cosmetic Surgery" },

  // Entertainment & Media  
  { value: "Movies", label: "Movies" },
  { value: "TV Shows", label: "TV Shows" },
  { value: "Anime", label: "Anime" },
  { value: "K-Dramas", label: "K-Dramas" },
  { value: "Music Albums", label: "Music Albums" },
  { value: "Concerts", label: "Concerts" },
  { value: "Streaming Services", label: "Streaming Services" },
  { value: "Video Games", label: "Video Games" },
  { value: "Board Games", label: "Board Games" },
  { value: "Comic Books", label: "Comic Books" },

  // Home & Living  
  { value: "Furniture", label: "Furniture" },
  { value: "Home Decor", label: "Home Decor" },
  { value: "Kitchenware", label: "Kitchenware" },
  { value: "Bedding", label: "Bedding" },
  { value: "Lighting", label: "Lighting" },
  { value: "Gardening", label: "Gardening" },
  { value: "Smart Home", label: "Smart Home" },
  { value: "Home Appliances", label: "Home Appliances" },
  { value: "Cleaning Supplies", label: "Cleaning Supplies" },
  { value: "Pet Supplies", label: "Pet Supplies" },

  // Health & Wellness  
  { value: "Vitamins", label: "Vitamins" },
  { value: "Protein Supplements", label: "Protein Supplements" },
  { value: "Weight Loss", label: "Weight Loss" },
  { value: "Yoga Mats", label: "Yoga Mats" },
  { value: "Fitness Equipment", label: "Fitness Equipment" },
  { value: "Mental Wellness", label: "Mental Wellness" },
  { value: "Medical Devices", label: "Medical Devices" },
  { value: "Elderly Care", label: "Elderly Care" },
  { value: "Sexual Wellness", label: "Sexual Wellness" },
  { value: "Essential Oils", label: "Essential Oils" },

  // Automotive  
  { value: "Cars", label: "Cars" },
  { value: "Motorcycles", label: "Motorcycles" },
  { value: "Bicycles", label: "Bicycles" },
  { value: "Tires", label: "Tires" },
  { value: "Car Audio", label: "Car Audio" },
  { value: "Car Accessories", label: "Car Accessories" },
  { value: "EV Chargers", label: "EV Chargers" },
  { value: "Auto Parts", label: "Auto Parts" },
  { value: "Car Wash", label: "Car Wash" },
  { value: "Vehicle Rentals", label: "Vehicle Rentals" },

  // Food & Beverage  
  { value: "Gourmet Food", label: "Gourmet Food" },
  { value: "Organic Food", label: "Organic Food" },
  { value: "Coffee & Tea", label: "Coffee & Tea" },
  { value: "Wine & Spirits", label: "Wine & Spirits" },
  { value: "Vegan Products", label: "Vegan Products" },
  { value: "Kitchen Gadgets", label: "Kitchen Gadgets" },
  { value: "Restaurant Deals", label: "Restaurant Deals" },
  { value: "Meal Kits", label: "Meal Kits" },
  { value: "Snacks", label: "Snacks" },
  { value: "Food Delivery", label: "Food Delivery" },

  // Travel & Leisure  
  { value: "Hotels", label: "Hotels" },
  { value: "Flight Tickets", label: "Flight Tickets" },
  { value: "Vacation Packages", label: "Vacation Packages" },
  { value: "Cruises", label: "Cruises" },
  { value: "Backpacks", label: "Backpacks" },
  { value: "Luggage", label: "Luggage" },
  { value: "Travel Insurance", label: "Travel Insurance" },
  { value: "Adventure Tours", label: "Adventure Tours" },
  { value: "Camping Gear", label: "Camping Gear" },
  { value: "Ski Resorts", label: "Ski Resorts" },

  // Business & Services  
  { value: "Freelance Services", label: "Freelance Services" },
  { value: "Web Hosting", label: "Web Hosting" },
  { value: "Domain Names", label: "Domain Names" },
  { value: "Office Supplies", label: "Office Supplies" },
  { value: "Printing Services", label: "Printing Services" },
  { value: "Virtual Assistants", label: "Virtual Assistants" },
  { value: "Business Coaching", label: "Business Coaching" },
  { value: "POS Systems", label: "POS Systems" },
  { value: "CRM Software", label: "CRM Software" },
  { value: "Accounting Tools", label: "Accounting Tools" },

  // Kids & Babies  
  { value: "Baby Clothing", label: "Baby Clothing" },
  { value: "Diapers", label: "Diapers" },
  { value: "Strollers", label: "Strollers" },
  { value: "Toys", label: "Toys" },
  { value: "Baby Food", label: "Baby Food" },
  { value: "Kids' Bikes", label: "Kids' Bikes" },
  { value: "Educational Toys", label: "Educational Toys" },
  { value: "Nursery Decor", label: "Nursery Decor" },
  { value: "Baby Monitors", label: "Baby Monitors" },
  { value: "Children's Books", label: "Children's Books" },

  // Hobbies & Collectibles  
  { value: "Trading Cards", label: "Trading Cards" },
  { value: "Action Figures", label: "Action Figures" },
  { value: "Model Kits", label: "Model Kits" },
  { value: "Vinyl Records", label: "Vinyl Records" },
  { value: "Art Supplies", label: "Art Supplies" },
  { value: "Musical Instruments", label: "Musical Instruments" },
  { value: "Drones (Hobby)", label: "Drones (Hobby)" },
  { value: "RC Cars", label: "RC Cars" },
  { value: "Coin Collecting", label: "Coin Collecting" },
  { value: "Stamp Collecting", label: "Stamp Collecting" },

  // Special Interest  
  { value: "Astrology", label: "Astrology" },
  { value: "Tarot Cards", label: "Tarot Cards" },
  { value: "Crystals", label: "Crystals" },
  { value: "Horror Merch", label: "Horror Merch" },
  { value: "Anime Merch", label: "Anime Merch" },
  { value: "K-Pop Merch", label: "K-Pop Merch" },
  { value: "Fantasy Books", label: "Fantasy Books" },
  { value: "Sci-Fi Collectibles", label: "Sci-Fi Collectibles" },
  { value: "Meditation Tools", label: "Meditation Tools" },
  { value: "Spiritual Retreats", label: "Spiritual Retreats" },
];