export const audienceTypeOptions = [
  // Age-Based
  { value: "Children", label: "Children (0-12)" },
  { value: "Teens", label: "Teens (13-19)" },
  { value: "Young Adults", label: "Young Adults (20-30)" },
  { value: "Millennials", label: "Millennials (25-40)" },
  { value: "Adults", label: "Adults (30-50)" },
  { value: "Middle Aged", label: "Middle Aged (40-60)" },
  { value: "Seniors", label: "Seniors (50+)" },
  { value: "Elderly", label: "Elderly (65+)" },

  // Professions
  { value: "Students", label: "Students" },
  { value: "College Students", label: "College Students" },
  { value: "Professionals", label: "Professionals" },
  { value: "Entrepreneurs", label: "Entrepreneurs" },
  { value: "Freelancers", label: "Freelancers" },
  { value: "Remote Workers", label: "Remote Workers" },
  { value: "Healthcare Workers", label: "Healthcare Workers" },
  { value: "Teachers", label: "Teachers" },
  { value: "Engineers", label: "Engineers" },
  { value: "IT Professionals", label: "IT Professionals" },
  { value: "Artists", label: "Artists" },
  { value: "Creatives", label: "Creatives (Designers, Writers)" },
  { value: "Blue Collar Workers", label: "Blue Collar Workers" },
  { value: "Executives", label: "Executives" },
  { value: "Retirees", label: "Retirees" },

  // Family & Lifestyle
  { value: "Parents", label: "Parents" },
  { value: "New Parents", label: "New Parents (0-3 years)" },
  { value: "Single Parents", label: "Single Parents" },
  { value: "Homeowners", label: "Homeowners" },
  { value: "Renters", label: "Renters" },
  { value: "Pet Owners", label: "Pet Owners" },
  { value: "Dog Owners", label: "Dog Owners" },
  { value: "Cat Owners", label: "Cat Owners" },
  { value: "Fitness Enthusiasts", label: "Fitness Enthusiasts" },
  { value: "Gamers", label: "Gamers" },
  { value: "Travelers", label: "Travelers" },
  { value: "Frequent Flyers", label: "Frequent Flyers" },
  { value: "Foodies", label: "Foodies" },
  { value: "Vegetarians", label: "Vegetarians" },
  { value: "Vegans", label: "Vegans" },

  // Interests & Hobbies
  { value: "Tech Enthusiasts", label: "Tech Enthusiasts" },
  { value: "Photographers", label: "Photographers" },
  { value: "Musicians", label: "Musicians" },
  { value: "Book Lovers", label: "Book Lovers" },
  { value: "Movie Buffs", label: "Movie Buffs" },
  { value: "Anime Fans", label: "Anime Fans" },
  { value: "Sports Fans", label: "Sports Fans" },
  { value: "Outdoor Adventurers", label: "Outdoor Adventurers" },
  { value: "Gardening Enthusiasts", label: "Gardening Enthusiasts" },
  { value: "DIYers", label: "DIYers" },
  { value: "Luxury Shoppers", label: "Luxury Shoppers" },
  { value: "Thrift Shoppers", label: "Thrift Shoppers" },
  { value: "Investors", label: "Investors" },
  { value: "Minimalists", label: "Minimalists" },
  { value: "Environmentalists", label: "Environmentalists" }
];