export const pageContentCategoryOptions = [
  // Technology & Digital
  { value: "Artificial Intelligence", label: "Artificial Intelligence" },
  { value: "Blockchain & Crypto", label: "Blockchain & Crypto" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Programming", label: "Programming" },
  { value: "Web Development", label: "Web Development" },
  { value: "Mobile Apps", label: "Mobile Apps" },
  { value: "Gadget Reviews", label: "Gadget Reviews" },
  { value: "Tech News", label: "Tech News" },
  { value: "Software Tutorials", label: "Software Tutorials" },
  { value: "Cloud Computing", label: "Cloud Computing" },

  // Business & Finance
  { value: "Startups", label: "Startups" },
  { value: "Entrepreneurship", label: "Entrepreneurship" },
  { value: "Digital Marketing", label: "Digital Marketing" },
  { value: "Stock Market", label: "Stock Market" },
  { value: "Personal Finance", label: "Personal Finance" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "E-commerce", label: "E-commerce" },
  { value: "Leadership", label: "Leadership" },
  { value: "Productivity", label: "Productivity" },
  { value: "Remote Work", label: "Remote Work" },

  // Entertainment
  { value: "Movie Reviews", label: "Movie Reviews" },
  { value: "TV Show Recaps", label: "TV Show Recaps" },
  { value: "Celebrity News", label: "Celebrity News" },
  { value: "Music Releases", label: "Music Releases" },
  { value: "Anime & Manga", label: "Anime & Manga" },
  { value: "K-pop Culture", label: "K-pop Culture" },
  { value: "Broadway & Theater", label: "Broadway & Theater" },
  { value: "Comedy", label: "Comedy" },
  { value: "Fan Theories", label: "Fan Theories" },
  { value: "Reality TV", label: "Reality TV" },

  // Gaming
  { value: "Game Reviews", label: "Game Reviews" },
  { value: "Esports", label: "Esports" },
  { value: "Gaming News", label: "Gaming News" },
  { value: "Walkthroughs", label: "Walkthroughs" },
  { value: "Retro Gaming", label: "Retro Gaming" },
  { value: "VR Gaming", label: "VR Gaming" },
  { value: "Mobile Gaming", label: "Mobile Gaming" },
  { value: "Gaming Setup", label: "Gaming Setup" },
  { value: "Game Development", label: "Game Development" },
  { value: "Cosplay", label: "Cosplay" },

  // Science & Education
  { value: "Space Exploration", label: "Space Exploration" },
  { value: "Physics", label: "Physics" },
  { value: "Biology", label: "Biology" },
  { value: "Chemistry", label: "Chemistry" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Psychology", label: "Psychology" },
  { value: "Neuroscience", label: "Neuroscience" },
  { value: "Climate Science", label: "Climate Science" },
  { value: "Archaeology", label: "Archaeology" },
  { value: "Paleontology", label: "Paleontology" },

  // Travel
  { value: "Budget Travel", label: "Budget Travel" },
  { value: "Luxury Travel", label: "Luxury Travel" },
  { value: "Adventure Travel", label: "Adventure Travel" },
  { value: "Solo Travel", label: "Solo Travel" },
  { value: "Family Travel", label: "Family Travel" },
  { value: "Digital Nomads", label: "Digital Nomads" },
  { value: "Hotel Reviews", label: "Hotel Reviews" },
  { value: "Travel Hacks", label: "Travel Hacks" },
  { value: "Hidden Gems", label: "Hidden Gems" },
  { value: "Cultural Immersion", label: "Cultural Immersion" },

  // Fashion & Beauty
  { value: "Street Style", label: "Street Style" },
  { value: "Luxury Fashion", label: "Luxury Fashion" },
  { value: "Sustainable Fashion", label: "Sustainable Fashion" },
  { value: "Makeup Tutorials", label: "Makeup Tutorials" },
  { value: "Skincare Routine", label: "Skincare Routine" },
  { value: "Hair Care", label: "Hair Care" },
  { value: "Nail Art", label: "Nail Art" },
  { value: "Fashion History", label: "Fashion History" },
  { value: "Body Positivity", label: "Body Positivity" },
  { value: "Men's Grooming", label: "Men's Grooming" },

  // Food & Beverage
  { value: "Recipes", label: "Recipes" },
  { value: "Baking", label: "Baking" },
  { value: "Vegan Cooking", label: "Vegan Cooking" },
  { value: "Mixology", label: "Mixology" },
  { value: "Coffee Culture", label: "Coffee Culture" },
  { value: "Wine Tasting", label: "Wine Tasting" },
  { value: "Restaurant Reviews", label: "Restaurant Reviews" },
  { value: "Food Science", label: "Food Science" },
  { value: "International Cuisine", label: "International Cuisine" },
  { value: "Meal Prep", label: "Meal Prep" },

  // Health & Fitness
  { value: "Weight Loss", label: "Weight Loss" },
  { value: "Muscle Building", label: "Muscle Building" },
  { value: "Yoga", label: "Yoga" },
  { value: "Meditation", label: "Meditation" },
  { value: "Mental Health", label: "Mental Health" },
  { value: "Nutrition", label: "Nutrition" },
  { value: "Running", label: "Running" },
  { value: "Cycling", label: "Cycling" },
  { value: "Home Workouts", label: "Home Workouts" },
  { value: "Sports Medicine", label: "Sports Medicine" },

  // Lifestyle
  { value: "Minimalism", label: "Minimalism" },
  { value: "Parenting", label: "Parenting" },
  { value: "Relationships", label: "Relationships" },
  { value: "Self-Improvement", label: "Self-Improvement" },
  { value: "DIY Projects", label: "DIY Projects" },
  { value: "Home Organization", label: "Home Organization" },
  { value: "Gardening", label: "Gardening" },
  { value: "Pet Care", label: "Pet Care" },
  { value: "Sustainable Living", label: "Sustainable Living" },
  { value: "Feng Shui", label: "Feng Shui" },

  // Arts & Creativity
  { value: "Digital Art", label: "Digital Art" },
  { value: "Photography", label: "Photography" },
  { value: "Creative Writing", label: "Creative Writing" },
  { value: "Graphic Design", label: "Graphic Design" },
  { value: "Crafting", label: "Crafting" },
  { value: "Pottery", label: "Pottery" },
  { value: "Street Art", label: "Street Art" },
  { value: "Art History", label: "Art History" },
  { value: "Calligraphy", label: "Calligraphy" },
  { value: "Interior Design", label: "Interior Design" },

  // Sports
  { value: "Football", label: "Football" },
  { value: "Basketball", label: "Basketball" },
  { value: "Tennis", label: "Tennis" },
  { value: "Golf", label: "Golf" },
  { value: "Olympics", label: "Olympics" },
  { value: "Extreme Sports", label: "Extreme Sports" },
  { value: "Water Sports", label: "Water Sports" },
  { value: "Winter Sports", label: "Winter Sports" },
  { value: "Martial Arts", label: "Martial Arts" },
  { value: "Athlete Profiles", label: "Athlete Profiles" },

  // Automotive
  { value: "Car Reviews", label: "Car Reviews" },
  { value: "Electric Vehicles", label: "Electric Vehicles" },
  { value: "Classic Cars", label: "Classic Cars" },
  { value: "Car Maintenance", label: "Car Maintenance" },
  { value: "Racing", label: "Racing" },
  { value: "Motorcycles", label: "Motorcycles" },
  { value: "Bicycles", label: "Bicycles" },
  { value: "Auto Tech", label: "Auto Tech" },
  { value: "Off-Roading", label: "Off-Roading" },
  { value: "Car Culture", label: "Car Culture" },

  // Politics & Society
  { value: "Current Events", label: "Current Events" },
  { value: "Social Justice", label: "Social Justice" },
  { value: "Environmental Policy", label: "Environmental Policy" },
  { value: "Human Rights", label: "Human Rights" },
  { value: "Philosophy", label: "Philosophy" },
  { value: "History", label: "History" },
  { value: "Economics", label: "Economics" },
  { value: "Urban Planning", label: "Urban Planning" },
  { value: "Futurism", label: "Futurism" },
  { value: "Cultural Studies", label: "Cultural Studies" },

  // Special Interest
  { value: "True Crime", label: "True Crime" },
  { value: "Paranormal", label: "Paranormal" },
  { value: "Conspiracy Theories", label: "Conspiracy Theories" },
  { value: "Astrology", label: "Astrology" },
  { value: "Tarot", label: "Tarot" },
  { value: "Collectibles", label: "Collectibles" },
  { value: "Genealogy", label: "Genealogy" },
  { value: "Alternative Medicine", label: "Alternative Medicine" },
  { value: "Survivalism", label: "Survivalism" },
  { value: "Hobby Farming", label: "Hobby Farming" }
];